# Generated by Django 5.0.6 on 2024-06-13 20:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='expiration',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 13, 20, 12, 34, 606997, tzinfo=datetime.timezone.utc)),
        ),
    ]
