# Generated by Django 5.0.6 on 2024-06-17 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_otp_created_otp_updated_alter_otp_expiration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='otp',
            name='username',
            field=models.CharField(max_length=40),
        ),
    ]
