# Generated by Django 5.0.6 on 2024-06-16 12:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_otp_expiration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='expiration',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 16, 12, 58, 53, 527782, tzinfo=datetime.timezone.utc)),
        ),
    ]
