import type { Metadata } from "next";

import MainSideBar from "@/components/ui/sidebar";
import NavBar from "@/components/ui/navbar";

import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="fa" dir="rtl">
      <head>
      </head>
      <body>
        <NavBar />
        <MainSideBar />
        {children}
      </body>
    </html>
  );
}
