# Generated by Django 5.0.6 on 2024-06-14 09:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Beat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('published_status', models.CharField(choices=[('Draft', 'Draft'), ('Private', 'Private'), ('Published', 'Published')], default='Draft', max_length=9, verbose_name='published status')),
                ('status', models.CharField(choices=[('Accepted', 'Accepted'), ('Checking', 'Checking'), ('Rejected', 'Rejected')], default='Checking', max_length=8)),
                ('title', models.CharField(max_length=50)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('image', models.ImageField(blank=True, upload_to='beats/images')),
                ('beat_file', models.FileField(blank=True, upload_to='beats/files', verbose_name='beat file')),
                ('description', models.TextField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Beat_Owner', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Beat',
                'verbose_name_plural': 'Beats',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='BeatInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bpm', models.BigIntegerField(blank=True, null=True)),
                ('keys', models.CharField(blank=True, max_length=20, null=True)),
                ('publish', models.DateField(blank=True, null=True)),
                ('plays', models.IntegerField(default=0)),
                ('beat', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Beat_Info', to='beats.beat')),
            ],
            options={
                'verbose_name': 'Beat Information',
                'verbose_name_plural': 'Beats Information',
                'ordering': ['-beat'],
            },
        ),
    ]
