# Generated by Django 5.0.6 on 2024-06-16 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beats', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beat',
            name='published_status',
            field=models.CharField(choices=[('Draft', 'Draft'), ('Private', 'Private'), ('Published', 'Published')], default='Draft', max_length=9, verbose_name='published status'),
        ),
        migrations.AlterField(
            model_name='beat',
            name='status',
            field=models.CharField(choices=[('Accepted', 'Accepted'), ('Checking', 'Checking'), ('Rejected', 'Rejected')], default='Checking', max_length=8),
        ),
        migrations.AlterField(
            model_name='beat',
            name='title',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
