# Generated by Django 5.0.6 on 2024-06-16 13:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beats', '0003_alter_beat_managers_alter_beat_published_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='beat',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='beat',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Beat_Owner', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='beat',
            name='published_status',
            field=models.CharField(choices=[('Draft', 'Draft'), ('Private', 'Private'), ('Published', 'Published')], default='Draft', max_length=9, verbose_name='published status'),
        ),
        migrations.AlterField(
            model_name='beat',
            name='status',
            field=models.CharField(choices=[('Accepted', 'Accepted'), ('Checking', 'Checking'), ('Rejected', 'Rejected')], default='Checking', max_length=8),
        ),
    ]
