# Generated by Django 5.0.6 on 2024-06-24 09:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beats', '0008_alter_beat_owner'),
        ('categories', '0001_initial'),
        ('moods', '0001_initial'),
        ('tags', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='beat',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Beat_Category', to='categories.category'),
        ),
        migrations.AddField(
            model_name='beat',
            name='moods',
            field=models.ManyToManyField(blank=True, to='moods.mood'),
        ),
        migrations.AddField(
            model_name='beat',
            name='tags',
            field=models.ManyToManyField(blank=True, to='tags.tag'),
        ),
    ]
