# Generated by Django 5.0.6 on 2024-06-24 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beats', '0009_beat_category_beat_moods_beat_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='beat',
            name='category',
        ),
        migrations.RemoveField(
            model_name='beat',
            name='moods',
        ),
        migrations.RemoveField(
            model_name='beat',
            name='tags',
        ),
    ]
