# Generated by Django 5.0.6 on 2024-06-25 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beats', '0011_beatcategorisation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BeatCategorisation',
        ),
    ]
