# Generated by Django 5.0.6 on 2024-06-26 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beats', '0012_delete_beatcategorisation'),
        ('license', '0002_alter_beatlicenses_licenses'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BeatLicenses',
            new_name='BeatLicense',
        ),
        migrations.RenameModel(
            old_name='LicenseFiles',
            new_name='LicenseFile',
        ),
    ]
